#!/usr/bin/env bash
# Pulls WB_TOKEN and FORECAST_UI_TOKEN from Secret Manager and writes
# a 0600 EnvironmentFile consumed by the systemd units.
#
# Usage: fetch-secrets.sh <env-file> <data-dir>
#
# Idempotent. Safe to re-run to rotate secrets.

set -euo pipefail

ENV_FILE="${1:-/etc/wb-stocks.env}"
DATA_DIR="${2:-/srv/wb-stocks/data}"

if ! command -v gcloud >/dev/null; then
  echo "[fetch-secrets] FATAL: gcloud CLI not available" >&2
  exit 1
fi

get_secret() {
  local name="$1"
  gcloud secrets versions access latest --secret="$name" 2>/dev/null || true
}

WB_TOKEN_VALUE="$(get_secret WB_TOKEN)"
FORECAST_UI_TOKEN_VALUE="$(get_secret FORECAST_UI_TOKEN)"

if [[ -z "${WB_TOKEN_VALUE}" ]]; then
  echo "[fetch-secrets] WARN: WB_TOKEN secret is empty; WB API calls will fail" >&2
fi

# Write atomically: write to a tmp file, chmod, then mv.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<EOF
# Generated by deploy/gcp/scripts/fetch-secrets.sh — do not edit by hand.
WB_TOKEN=${WB_TOKEN_VALUE}
FORECAST_UI_TOKEN=${FORECAST_UI_TOKEN_VALUE}
FORECAST_UI_HOST=127.0.0.1
FORECAST_UI_PORT=3847
DATABASE_PATH=${DATA_DIR}/wb-stocks.sqlite
LOG_LEVEL=info
EOF

chmod 0640 "$TMP"
chown root:wbstocks "$TMP" 2>/dev/null || true
mv "$TMP" "$ENV_FILE"
trap - EXIT

echo "[fetch-secrets] wrote $ENV_FILE"
