#!/usr/bin/env bash
# Pulls application secrets from Secret Manager and writes
# a 0600 EnvironmentFile consumed by the systemd units.
#
# Usage: fetch-secrets.sh <env-file> <data-dir>
#
# Idempotent. Safe to re-run to rotate secrets.

set -euo pipefail

ENV_FILE="${1:-/etc/wb-stocks.env}"
DATA_DIR="${2:-/srv/wb-stocks/data}"

if ! command -v gcloud >/dev/null; then
  echo "[fetch-secrets] FATAL: gcloud CLI not available" >&2
  exit 1
fi

get_secret() {
  local name="$1"
  gcloud secrets versions access latest --secret="$name" 2>/dev/null || true
}

WB_TOKEN_VALUE="$(get_secret WB_TOKEN)"
FORECAST_UI_TOKEN_VALUE="$(get_secret FORECAST_UI_TOKEN)"
OPTICORE_USER_VALUE="$(get_secret OPTICORE_USER)"
OPTICORE_PASSWORD_VALUE="$(get_secret OPTICORE_PASSWORD)"
OPTICORE_BASE_URL_VALUE="$(get_secret OPTICORE_BASE_URL)"
OPTICORE_REPORTS_URL_VALUE="$(get_secret OPTICORE_REPORTS_URL)"
OPTICORE_HTTP_USER_VALUE="$(get_secret OPTICORE_HTTP_USER)"
OPTICORE_HTTP_PASSWORD_VALUE="$(get_secret OPTICORE_HTTP_PASSWORD)"
OPTICORE_WAREHOUSE_IDS_VALUE="$(get_secret OPTICORE_WAREHOUSE_IDS)"
OPTICORE_STOCK_TYPE_IDS_VALUE="$(get_secret OPTICORE_STOCK_TYPE_IDS)"
OPTICORE_VENDOR_CODE_SOURCE_VALUE="$(get_secret OPTICORE_VENDOR_CODE_SOURCE)"
OPTICORE_SKU_VENDOR_MAP_FILE_VALUE="$(get_secret OPTICORE_SKU_VENDOR_MAP_FILE)"

if [[ -z "${WB_TOKEN_VALUE}" ]]; then
  echo "[fetch-secrets] WARN: WB_TOKEN secret is empty; WB API calls will fail" >&2
fi
if [[ -z "${OPTICORE_USER_VALUE}" || -z "${OPTICORE_PASSWORD_VALUE}" ]]; then
  echo "[fetch-secrets] WARN: OptiCore credentials are empty; own warehouse stock refresh will be skipped" >&2
fi
if [[ -n "${OPTICORE_USER_VALUE}" && -n "${OPTICORE_PASSWORD_VALUE}" && -z "${OPTICORE_BASE_URL_VALUE}" && -z "${OPTICORE_REPORTS_URL_VALUE}" ]]; then
  echo "[fetch-secrets] WARN: OptiCore endpoint is empty; set OPTICORE_REPORTS_URL or OPTICORE_BASE_URL" >&2
fi

# Write atomically: write to a tmp file, chmod, then mv.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<EOF
# Generated by deploy/gcp/scripts/fetch-secrets.sh — do not edit by hand.
WB_TOKEN=${WB_TOKEN_VALUE}
FORECAST_UI_TOKEN=${FORECAST_UI_TOKEN_VALUE}
FORECAST_UI_HOST=127.0.0.1
FORECAST_UI_PORT=3847
DATABASE_PATH=${DATA_DIR}/wb-stocks.sqlite
LOG_LEVEL=info
OPTICORE_STOCK_REFRESH_ENABLED=true
OPTICORE_STOCK_FAILURE_MODE=warn
OPTICORE_BASE_URL=${OPTICORE_BASE_URL_VALUE}
OPTICORE_REPORTS_URL=${OPTICORE_REPORTS_URL_VALUE}
OPTICORE_USER=${OPTICORE_USER_VALUE}
OPTICORE_PASSWORD=${OPTICORE_PASSWORD_VALUE}
OPTICORE_HTTP_USER=${OPTICORE_HTTP_USER_VALUE}
OPTICORE_HTTP_PASSWORD=${OPTICORE_HTTP_PASSWORD_VALUE}
OPTICORE_TIMEOUT_MS=30000
OPTICORE_OWN_WAREHOUSE_CODE=main
OPTICORE_WAREHOUSE_IDS=${OPTICORE_WAREHOUSE_IDS_VALUE}
OPTICORE_STOCK_TYPE_IDS=${OPTICORE_STOCK_TYPE_IDS_VALUE:-0}
OPTICORE_VENDOR_CODE_SOURCE=${OPTICORE_VENDOR_CODE_SOURCE_VALUE:-sku_id}
OPTICORE_SKU_VENDOR_MAP_FILE=${OPTICORE_SKU_VENDOR_MAP_FILE_VALUE}
EOF

chmod 0640 "$TMP"
chown root:wbstocks "$TMP" 2>/dev/null || true
mv "$TMP" "$ENV_FILE"
trap - EXIT

echo "[fetch-secrets] wrote $ENV_FILE"
